### ISSUE TITLE
Release 21.12.0

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/self-hosted#1193]
This release carries more risk than usual because of #796. I'm making a ticket here to remember some things to pay attention to.

- [x] during the `sentry` release, make sure that the [status provider check](https://github.com/getsentry/sentry/blob/master/.craft.yml#L9) lines up name-wise with the check as named in GCB (see [this thread](https://github.com/getsentry/sentry/pull/30483/files#r764391302))
- [x] prep milestones
- [x] add something in the changelog about #1196 (statement that we are not vulnerable)

**Comment by chadwhitacre** [comment]
The changelog for tomorrow is actually going to be tricky because we don't have a PR related to #1196, and craft's auto mechanism assumes PRs/commits for every changelog entry. I read craft code and tested out putting an "Unreleased" section but that simply gets updated to the new version without actually listing all of the new material.

**Comment by chadwhitacre** [comment]
What I am going to try is manually modifying the CHANGELOG.md on the `release/21.12.0` branch after the prepare action is run but before ... oh wait, CalVer releases are auto-accepted. I guess we need a release blocker? Nope, that prevents event the action-prepare-release from completing.

Okay, plan C: Make a dummy commit related to the milestone in order to work with the existing changelog infra.

**Comment by chadwhitacre** [comment]
> prep milestones

Seeing these to account for:

- [ ] Rename onpremise to self-hosted (#1169)
- [ ] Unfrobulate "cleanup" in integration test (#1170)
- [ ] Revert "Rename onpremise to self-hosted" (5495fe2e)
- [ ] Rename onpremise to self-hosted (9ad05d87)
- [ ] Add support for custom DotEnv file (#1113)
- [ ] Sentry styleguide, I did this on the other (#1167)
- [ ] Remove link to forum (#1151) (#1160)
- [ ] Tweak issue forms (#1159)
- [ ] Bump nginx:1.21.4-alpine (#1156)

**Comment by chadwhitacre** [comment]
Bloop. Can't retroactively skip commits (re: garbage 5495fe2 9ad05d8).

**Comment by chadwhitacre** [comment]
```
$ craft prepare --no-push 21.12.0
$ head -n45 CHANGELOG.md
```

# Changelog

## 21.12.0

### Support Docker Compose v2 (ongoing)

Self-hosted Sentry mostly works with Docker Compose v2 (in addition to v1 >= 1.28.0). There is [one more bug](https://github.com/getsentry/self-hosted/issues/1133) we are trying to squash.

By: @chadwhitacre (#1179)

### Prevent Component Drift

When a user runs the `install.sh` script, they get the latest version of the Sentry, Snuba, Relay and Symbolicator projects. However there is no guarantee they have pulled the latest `self-hosted` version first, and running an old one may cause problems. To mitigate this, we now perform a check during installation that the user is on the latest commit if they are on the `master` branch. You can disable this check with `--skip-commit-check`.

By: @chadwhitacre (#1191), @aminvakil (#1186)

### React to log4shell

Self-hosted Sentry is [not vulnerable](https://github.com/getsentry/self-hosted/issues/1196) to the [log4shell](https://log4shell.com/) vulnerability.

By: @chadwhitacre (#1203)

### Forum → Issues

In the interest of reducing sources of truth and restarting the fire of the self-hosted Sentry community, we [deprecated the Discourse forum in favor of GitHub Issues](https://github.com/getsentry/self-hosted/issues/1151).

By: @chadwhitacre (#1167, #1160, #1159)

### Rename onpremise to self-hosted (ongoing)

In the beginning we used the term "on-premise" and over time we introduced the term "self-hosted." In an effort to regain some consistency for both branding and developer mental overhead purposes we are standardizing on the term "self-hosted." This release includes a fair portion of the work in code towards this, hopefully a future release will include the remainder. The effect of this as a self-hosted user will be that you will see orphaned blah blah blah you need to clean those up floo flah how

By: @chadwhitacre (#1169)

### Add support for custom DotEnv file

There are several ways to [configure self-hosted Sentry](https://develop.sentry.dev/self-hosted/&#35;configuration) and one of them is the `.env` file. In this release we add support for a `.env.custom` file that is git-ignored to make it easier for you to override keys configured this way with custom values. Thanks to @Sebi94nbg for the contribution!

By: @Sebi94nbg (#1113)

### Various fixes & improvements

- Revert "Rename onpremise to self-hosted" (5495fe2e) by @chadwhitacre
- Rename onpremise to self-hosted (9ad05d87) by @chadwhitacre

**Comment by chadwhitacre** [comment]
Gosh shouldn't we link to the changelogs for all of the components, as well? I'm thinking of https://github.com/getsentry/self-hosted/issues/1131.

**Comment by chadwhitacre** [comment]
Milestones ready.

**Comment by BYK** [comment]
@chadwhitacre you could have blocked the release, prepare locally, edit the Changelog in the release branch, and then finalize the release.

I think we should document this process and potentially find a way to easily edit the changelog before it goes out.

The issue is automation and manual editing are things are at odds so the best I can think of it is having a mechanism like you offered: allow having an `unreleased` section which gets prepended (or appended?) to the auto-generated changelog.

Happy to dive into Craft code after a while if this sounds like a good idea.

**Comment by chadwhitacre** [comment]
Sentry failure:

```
Error:  Validation Failed: ***"resource":"Release","code":"custom","field":"body","message":"body is too long (maximum is 125000 characters)"***
```

Presuming this has to do with the changelog.

**Comment by chadwhitacre** [comment]
Snuba and Relay are out, fwiw.

**Comment by chadwhitacre** [comment]
https://github.com/getsentry/sentry/blob/releases/21.12.0/CHANGES

**Comment by chadwhitacre** [comment]
Here's [the failing call](https://github.com/getsentry/craft/blob/95677da7d2f8c15df19cf1bd6369bdeb77209b3b/src/targets/github.ts#L229-L231):

```js
      const created = await this.github.repos.createRelease(
        createReleaseParams
      );
```

Here's [the payload](https://github.com/getsentry/craft/blob/95677da7d2f8c15df19cf1bd6369bdeb77209b3b/src/targets/github.ts#L205-L214):

```js
    const createReleaseParams = {
      draft: false,
      name: tag,
      owner: this.githubConfig.owner,
      prerelease: isPreview,
      repo: this.githubConfig.repo,
      tag_name: tag,
      target_commitish: revision,
      ...changes,
    };
```

`...changes` 🧐

**Comment by chadwhitacre** [comment]
https://github.com/getsentry/sentry/blob/releases/21.12.0/CHANGES#L32-L1701

Blech, forgot about https://github.com/getsentry/craft/issues/327 tho. :(

**Comment by chadwhitacre** [comment]
Okay, I did a little poking at https://github.com/getsentry/craft/pull/327. I'm not going to try to engineer a fix for that atm.

Also, I have a review on https://github.com/getsentry/craft/pull/335, but I don't think I'm going to try to use that for this release, in the interest of minimizing variability.

I think my plan at this point is to:

- [ ] Manually modify the [changelog on the `release/21.12.0` branch in `sentry`](https://github.com/getsentry/sentry/blob/releases/21.12.0/CHANGES). Due to 327 it's not going to get merged back to `master` anyway. 🙄
- [ ] Re-`accept` https://github.com/getsentry/publish/issues/700. As I [read/understand it](https://github.com/getsentry/craft/blob/95677da7d2f8c15df19cf1bd6369bdeb77209b3b/src/commands/publish.ts#L471-L489) `craft` will pick up with a pre-existing branch in whatever state it's in.
- [ ] Manually make a PR to `sentry` after the release to update the changelog for the last three releases (including today's).

**Comment by BYK** [comment]
>Manually modify the changelog on the release/21.12.0 branch in sentry. Due to 327 it's not going to get merged back to master anyway. 🙄

This is an excellent workaround. You can still use the publish flow for this.

>Manually make a PR to sentry after the release to update the changelog for the last three releases (including today's).

Is this because of the wrong merge base?

**Comment by BYK** [comment]
> Re-accept publish: getsentry/sentry@21.12.0 publish#700. As I read/understand it craft will pick up with a pre-existing branch in whatever state it's in.

Yes, it will use the existing branch.

**Comment by chadwhitacre** [comment]
> You can still use the publish flow for this.

Meaning "Re-accept [the publish ticket]"?

> Is this because of the wrong merge base?

Yes.

**Comment by chadwhitacre** [comment]
https://github.com/getsentry/sentry/runs/4538784692?check_suite_focus=true 🍿

**Comment by chadwhitacre** [comment]
Prepping the repaired `CHANGES` file ...

https://github.com/getsentry/sentry/blob/21.12.0/CHANGES
https://github.com/getsentry/sentry/blob/21.11.0/CHANGES
https://github.com/getsentry/sentry/blob/21.10.0/CHANGES

**Comment by chadwhitacre** [comment]
CI is green for the CHANGES repair on the branch, I reaccepted the ticket. Technically this will be a different artifact than what we uploaded to PyPI and Docker, but the only delta is in the changelog so meh.

**Comment by chadwhitacre** [comment]
https://github.com/getsentry/publish/runs/4539048239?check_suite_focus=true 🍿

**Comment by chadwhitacre** [comment]
Was about to say ... need to whack the old `21.12.0` tag ...

**Comment by chadwhitacre** [comment]
Here's the [original 21.12.0 tag for reference](https://github.com/getsentry/sentry/tree/14f603cf3ff1e6d31f10eac9513780bc6d31981d/).

**Comment by chadwhitacre** [comment]
ftr

```
-rw-r--r--   1 chadwhitacre  staff     2835 Dec 15 12:03 CHANGES-21.10.0
-rw-r--r--   1 chadwhitacre  staff    38775 Dec 15 12:03 CHANGES-21.10.0-more
-rw-r--r--   1 chadwhitacre  staff     3178 Dec 15 12:02 CHANGES-21.11.0
-rw-r--r--   1 chadwhitacre  staff    90988 Dec 15 12:01 CHANGES-21.11.0-more
-rw-r--r--   1 chadwhitacre  staff     3305 Dec 15 11:59 CHANGES-21.12.0
-rw-r--r--   1 chadwhitacre  staff   132410 Dec 15 11:59 CHANGES-21.12.0-more
```

**Comment by chadwhitacre** [comment]
Sentry is out! 💃

**Comment by chadwhitacre** [comment]
https://github.com/getsentry/sentry/actions/runs/1584492692 🍿

**Comment by chadwhitacre** [comment]
Alright, while the sentry changelog repair bakes in CI, I'm going to kick off the `self-hosted` deploy ...

**Comment by chadwhitacre** [comment]
I'm trying out a "Re-run all jobs" [here](https://github.com/getsentry/self-hosted/runs/4537928018?check_suite_focus=true). 🤞

**Comment by chadwhitacre** [comment]
Removed release branch, retrying ...

**Comment by chadwhitacre** [comment]
https://github.com/getsentry/publish/issues/704 sloggin' ... now what?

**Comment by chadwhitacre** [comment]
>  Build(s) for revision 63bb01c9bc2fed678c1686600a4ec8e2e633fe61 have not succeeded. Please check the revision's status.

https://github.com/getsentry/publish/runs/4539456662?check_suite_focus=true#step:8:52

Did we run afoul of #1171? 🧐

**Comment by chadwhitacre** [comment]
Hmmm ... not familiar. 🤔 

```
Unable to find image 'busybox:latest' locally
  docker: Error response from daemon: Head "https://registry-1.docker.io/v2/library/busybox/manifests/latest": unauthorized: incorrect username or password.
```

Gonna retry just in case ...

**Comment by chadwhitacre** [comment]
https://github.com/getsentry/self-hosted/actions/runs/1584537387 🍿

**Comment by BYK** [comment]
That was a Docker Hub blip (had a very similar error on my internal builds here around the same time)

**Comment by chadwhitacre** [comment]
Third time's the charm? 🙈

**Comment by chadwhitacre** [comment]
It seems that changing the `21.12.0` tag on `sentry` resulted in a corrupt build cache in GitHub Actions. `getsentry` builds are currently failing and we've opened an incident internally. I am keeping an eye here but primarily focused there.

**Comment by chadwhitacre** [comment]
https://github.com/getsentry/self-hosted/actions/runs/1584537387 🍿

**Comment by chadwhitacre** [comment]
Failing ... where is the relay release?

https://github.com/getsentry/relay/releases

**Comment by chadwhitacre** [comment]
https://github.com/getsentry/publish/issues/699

**Comment by chadwhitacre** [comment]
Seems like [it exited early](https://github.com/getsentry/publish/runs/4537264168?check_suite_focus=true#step:8:866)?

```
[debug] [[artifact-provider/github]] Downloading ZIP from Github artifacts...
```

**Comment by chadwhitacre** [comment]
[Successful run for comparison](https://github.com/getsentry/publish/runs/4217943866?check_suite_focus=true#step:8:65).

**Comment by chadwhitacre** [comment]
Okay, do we have a branch and tag on `relay`?

**Comment by chadwhitacre** [comment]
Doesn't look like it:

200 https://github.com/getsentry/relay/tree/21.11.0
404 https://github.com/getsentry/relay/tree/releases/21.11.0

404 https://github.com/getsentry/relay/tree/21.12.0
404 https://github.com/getsentry/relay/tree/releases/21.12.0

**Comment by chadwhitacre** [comment]
Branch: yes, tag: no. That's good. 👍

Re-accepting https://github.com/getsentry/publish/issues/699 ...

**Comment by chadwhitacre** [comment]
[Laugh or cry](https://github.com/getsentry/publish/runs/4540082749?check_suite_focus=true#step:8:169).

```
✖ Cannot upload asset "relay-Darwin-x86_64-dsym.zip".
Error:  request to https://uploads.github.com/repos/getsentry/relay/releases/55404236/assets?name=relay-Darwin-x86_64-dsym.zip& failed, reason: socket hang up
```

I saw this before ...

**Comment by chadwhitacre** [comment]
I forget what happened last time, I feel like it was a mess. Like, I tried to start over and it was a mess.

Finding one reference in Slack, dead end. Nada [on GitHub](https://github.com/search?q=org%3Agetsentry+%22cannot+upload+asset%22).

**Comment by chadwhitacre** [comment]
It was probably in a Slack thread that is gone now. Reason to do this here in GitHub instead.

**Comment by chadwhitacre** [comment]
Oh gosh, I think I ended up recreating the release object in GitHub manually? And it was a total cluster?

**Comment by chadwhitacre** [comment]
Yeah it was last month, this one has my name on it:

https://github.com/getsentry/sentry/releases/tag/21.11.0

**Comment by chadwhitacre** [comment]
Sweet! Slack thread still exists! 👍

**Comment by chadwhitacre** [comment]
> I'm going to start with relay since it's simpler. My plan is to delete the 21.11.0 release and rerun the release via publish repo.

Going to do the same here.

**Comment by chadwhitacre** [comment]
https://github.com/getsentry/publish/runs/4540347242?check_suite_focus=true 🍿

**Comment by chadwhitacre** [comment]
Failed again ..

**Comment by chadwhitacre** [comment]
Forgot to remove the tag.

**Comment by chadwhitacre** [comment]
https://github.com/getsentry/publish/runs/4540398196?check_suite_focus=true 🍿

**Comment by chadwhitacre** [comment]
Made it past GitHub. 👍

**Comment by chadwhitacre** [comment]
Okay! Relay is really out this time.

**Comment by chadwhitacre** [comment]
Back to self-hosted ...

**Comment by chadwhitacre** [comment]
Exfiltrating the steps to recover from "Cannot upload asset" for `sentry` in 21.11.0 as it was much more complicated:

> On to Sentry ...
> Tag and release deleted.
> Hrm, actually, the publish ticket claims to have already published everything but GitHub.
> I'm going to retag 21.11.0 and rerun.
> Fail.
> :disappointed:
> Reference "refs/tags/21.11.0" already exists. Does tag "21.11.0" already exist?
> If the tag exists it also wants the release to exist.
> If the release were still there it would proceed, and delete assets before re-uploading.
> Since the tag would be in the same place the assets would end up the same as on the previous run.
> So I either recreate the GH release object manually, or remove ...................................
> I'm unraveling how SHA gets passed from the publish issue to the craft publish invocation.
> I think I need to delete the tag and rerun. I think it pulls the commit from the ... no, it doesn't.
> It deploys master every time, afaict.
> I'm going to try manually creating a release object for 21.11.0 and rerunning to populate with assets.
> I stubbed it out, I will see about a changelog later.
> sentry artifacts are up, I'm going to restart onpremise and then work on sentry changelog.
> Rerunning test suite for onpremise.
> [changelog blah blah]
> onpremise suite passed, rerunning publish for onpremise.
> onpremise is out, so the release is done, except for the changelog on the sentry release.

Then I discovered https://github.com/getsentry/craft/issues/327.

**Comment by chadwhitacre** [comment]
Oh right #1171 ...

**Comment by chadwhitacre** [comment]
Oh right it was missing releay 21.12.0 ... 😅

**Comment by chadwhitacre** [comment]
https://github.com/getsentry/self-hosted/actions/runs/1584537387 🍿

**Comment by chadwhitacre** [comment]
Green! Re-accepting https://github.com/getsentry/publish/issues/704 ...

**Comment by chadwhitacre** [comment]
Done.

**Comment by chadwhitacre** [comment]
# Post-Mortem

This was anecdotally the most difficult self-hosted release since I started a year ago. Issues:

3. `snuba` - no issues THAT I KNOW OF
3. `sentry-docs`
    1. https://github.com/getsentry/publish/issues/705
3. `relay`
    1. [silent failure](https://github.com/getsentry/self-hosted/issues/1193#issuecomment-995224239) - not sure why
        1. if recurs frequently debug/address
        1. bare minimum: confirm that release actually exists once publish ticket closes
    1. intermittent asset upload failure from GitHub
        1. worked around by deleting the tag and release object and re-accepting the issue
        2. case contributing to https://github.com/getsentry/craft/issues/336
        3. probably worth retrying ... https://github.com/getsentry/craft/issues/337
3. `sentry`
    1. Changelog too large, failed to create GitHub release object
        1. Cut a new craft release with https://github.com/getsentry/craft/pull/335 before next self-hosted release
    1. https://github.com/getsentry/craft/issues/327
        1. Make manual PRs to update changelog post-release
    1. [INC-87](https://getsentry.atlassian.net/browse/INC-87) - delete/recreate tag while addressing (i) led to corrupted pip cache in test image for `getsentry`, resulting in red CI
        1. New issue: https://github.com/getsentry/craft/issues/336
3. `self-hosted`
    1. Friction around changelog due to #1196 and [garbage commits](https://github.com/getsentry/self-hosted/issues/1193#issuecomment-994181122)
        1. add `release-blocker` to the release ticket (i.e., this one), manually edit changelog on release branch, and proceed
    1. Slowed down by #1171 

General pattern: something something tags something something. I feel like a number of failure modes end up with us having to recreate a tag, and this can actually be catastrophic (inc-87).

**Comment by BYK** [comment]
>relay
>    silent failure - not sure why 

This looks like some terrible GitHub mishap. I actually got the Relay release email so my guess is either the job or the logs are corrupted. I'd file a support ticket with a link so they can investigate before the logs disappear.

>bare minimum: confirm that release actually exists once publish ticket closes

I don't think you need an extra step for this as Craft should crash itself causing the job to fail. If the release is out, self-hosted release would fail anyway.

>add release-blocker to the release ticket (i.e., this one), manually edit changelog on release branch, and proceed

I think this process needs to be documented and maybe even streamlined.

**Comment by chadwhitacre** [comment]
> I'd file a support ticket

Done. I cc'd you. 👍

> self-hosted release would fail anyway

Yeah, that's in fact how I [noticed](https://github.com/getsentry/self-hosted/issues/1193#issuecomment-995220313) that relay had not succeeded (even though it seemed it had). Hopefully a rare case. Not a big action item here more just a note to self.

> I think this process needs to be documented and maybe even streamlined.

https://github.com/getsentry/publish/issues/710 👍

**Comment by chadwhitacre** [comment]
Sharing out GH support thread for posterity:

>> Hi Chad,
>> 
>> Since you are running the Docker action docker://getsentry/craft:latest, the runner will simply run docker run getsentry/craft:latest and wait for docker to exit. The runner will mark the step succeed as long as the entry process for the step exit with return code 0.
>> 
>> You might want to add some trace and debug for the container to see why it is exiting without properly erroring out. One thing we've noticed is the bad run seems to go on for a long time compared to the good one.
>>
>> ![unnamed](https://user-images.githubusercontent.com/134455/147709336-245f982e-949d-4c5d-949d-2147389ee6c0.png)
>> ![unnamed (1)](https://user-images.githubusercontent.com/134455/147709334-29afa2c4-2560-4a47-a9ee-a037a00507c8.png)
>> 
>> 25m vs 2m
>> 
>> Best,
>> 
>> [GH support]
>>
> Could this be some system-level container killer scenario? Or a timeout?
>
> @BYK

Even if it is a system-level timeout or reaper, it seems that they are making us responsible for the container taking so long. Leaving this here for future discoverability in case of a repeat, but I don't think we need to take any further action now.

**Comment by chadwhitacre** [comment]
My original post to them for context:

> We [saw behavior yesterday](https://github.com/getsentry/self-hosted/issues/1193#issuecomment-995220313) where a GitHub Action was marked successful but did not run to completion.
> 
> Here is [the bad run, showing a truncated log](https://github.com/getsentry/publish/runs/4537264168?check_suite_focus=true#step:8:866):
> 
> ```
> [debug] [[status-provider/github]] Got status "success" for revision 91e58909b0dfeb3bbc464a12f10a2c1f714ced6b
> [info] [[status-provider/github]] Revision 91e58909b0dfeb3bbc464a12f10a2c1f714ced6b has been built successfully.
> [debug] [[artifact-provider/github]] Fetching artifact list for revision `91e58909b0dfeb3bbc464a12f10a2c1f714ced6b`.
> [info] [[artifact-provider/github]] Fetching Github artifacts for getsentry/relay, revision 91e58909b0dfeb3bbc464a12f10a2c1f714ced6b
> [debug] GET /repos/getsentry/relay/actions/artifacts?per_page=100&page=0 - 200 in 286ms
> [debug] [[artifact-provider/github]] Requesting archive URL from Github...
> [debug] GET /repos/getsentry/relay/actions/artifacts/126993957/zip - 200 in 20299ms
> [debug] [[artifact-provider/github]] Downloading ZIP from Github artifacts...
> ```
>
> Here is [a good run for comparison](https://github.com/getsentry/publish/runs/4217943866?check_suite_focus=true#step:8:65), showing the continuation of the log:
>
> ``` 
> [debug] [[status-provider/github]] Got status "success" for revision 2bef2ac8e891048e1f048cba1b5b7ec68d8a2192
> [info] [[status-provider/github]] Revision 2bef2ac8e891048e1f048cba1b5b7ec68d8a2192 has been built successfully.
> [debug] [[artifact-provider/github]] Fetching artifact list for revision `2bef2ac8e891048e1f048cba1b5b7ec68d8a2192`.
> [info] [[artifact-provider/github]] Fetching Github artifacts for getsentry/relay, revision 2bef2ac8e891048e1f048cba1b5b7ec68d8a2192
> [debug] GET /repos/getsentry/relay/actions/artifacts?per_page=100&page=0 - 200 in 298ms
> [debug] [[artifact-provider/github]] Requesting archive URL from Github...
> [debug] GET /repos/getsentry/relay/actions/artifacts/114545885/zip - 200 in 20178ms
> [debug] [[artifact-provider/github]] Downloading ZIP from Github artifacts...
> [info] [[artifact-provider/github]] Finished downloading.
> [debug] [[artifact-provider/github]] Extracting "/tmp/craft-1IJdRJnUoFR6o" to "/tmp/craft-ruzZTh"...
> [debug] [[artifact-provider/github]] Found 6 artifacts.
> [info]  
> [info] Available artifacts: 
> ┌──────────────────────────────┬──────────┬─────────┬─────────────┐
> │ File Name                    │ Size     │ Updated │ ContentType │
> ├──────────────────────────────┼──────────┼─────────┼─────────────┤
> │ relay-Darwin-x86_64          │ 30.98 MB │         │             │
> ├──────────────────────────────┼──────────┼─────────┼─────────────┤
> │ relay-Darwin-x86_64-dsym.zip │ 58.00 MB │         │             │
> ├──────────────────────────────┼──────────┼─────────┼─────────────┤
> │ relay-Linux-x86_64           │ 20.68 MB │         │             │
> ├──────────────────────────────┼──────────┼─────────┼─────────────┤
> │ relay-Linux-x86_64-debug.zip │ 77.97 MB │         │             │
> ├──────────────────────────────┼──────────┼─────────┼─────────────┤
> │ relay-Windows-x86_64-pdb.zip │ 35.34 MB │         │             │
> ├──────────────────────────────┼──────────┼─────────┼─────────────┤
> │ relay-Windows-x86_64.exe     │ 18.52 MB │         │             │
> └──────────────────────────────┴──────────┴─────────┴─────────────┘
> ```
>
> The expected output of the run is [a new release entry here](https://github.com/getsentry/relay/releases). For the bad run, no release appeared on that page ...
> 
> ... but! A collaborator reported that [they did receive the release email](https://github.com/getsentry/self-hosted/issues/1193#issuecomment-995524693) for the bad run:
> 
>> I actually got the Relay release email so my guess is either the job or the logs are corrupted. I'd file a support ticket with a link so they can investigate before the logs disappear.
> 
> ... and here we are. :-)
