### ISSUE TITLE
Figure out what's up with client reports

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/self-hosted#1432]
> Client reports are a protocol feature that let clients send status reports about themselves to Sentry. They are currently mainly used to emit outcomes for events that were never sent. Chained relays are also able to emit these client reports to inform the next relay in chain about some outcomes.
>
> Due to a bug in Relay, which discards envelopes containing unknown envelope items, the minimum required version of Sentry for client reports is [21.9.0](https://github.com/getsentry/relay/blob/master/CHANGELOG.md#2190).

https://develop.sentry.dev/sdk/client-reports/

What versions of what SDKs send client reports?

- [ ] `sentry-python` since [1.4.0](https://github.com/getsentry/sentry-python/blob/master/CHANGELOG.md#140)
- [ ] `sentry-cocoa` since [7.13.0](https://github.com/getsentry/sentry-cocoa/blob/master/CHANGELOG.md#7130)
- [ ] `sentry-javascript` since [6.13.0](https://github.com/getsentry/sentry-javascript/blob/master/CHANGELOG.md#6130)
- [ ] `sentry-java` will be in [6.0.0](https://github.com/getsentry/sentry-java/blob/6.x.x/CHANGELOG.md#600-alpha6)
- [ ] `sentry-dart` soon see https://github.com/getsentry/sentry-dart/pull/829
- [ ] `sentry-dotnet` soon see https://github.com/getsentry/sentry-dotnet/pull/1556

What version of Relay introduced the bug that causes us to drop envelopes containing client reports?

**Comment by marandaneto** [comment]
sentry-dart, 6.6.0 (not yet published)
sentry-java, 6.0.0 (still alpha)
sentry-cocoa, 7.13.0 (GA)

**Comment by jan-auer** [comment]
> What version of Relay introduced the bug that causes us to drop envelopes containing client reports?

It has always been this way, from introducing Envelopes. Relay never accepted unknown item types while it should've. This being fixed through https://github.com/getsentry/relay/pull/1246

**Comment by philipphofmann** [comment]
> Honestly this info should probably end up on that doc https://develop.sentry.dev/sdk/client-reports/

It already is there @chadwhitacre.

**Comment by chadwhitacre** [comment]
I meant the details about SDK versions. This would be a great use case for an automated capabilities matrix in https://github.com/getsentry/sentry-release-registry

**Comment by chadwhitacre** [comment]
@mitsuhiko Is this the one where we talked about SDKs reporting an issue into the self-hosted instance if they detect the server version is too low? We were approaching from marketing / incentivizing upgrade angle.

**Comment by chadwhitacre** [comment]
I have a [note](https://github.com/getsentry/self-hosted/issues/1422) to add something to the release notes for self-hosted about this, but I'm not sure what I'm supposed to say. I think for people upgrading to the latest self-hosted there is no action item, correct? The action item is for people who have upgrade their SDK _without_ upgrading self-hosted (past 21.9.0), correct?

**Comment by jan-auer** [comment]
> The action item is for people who have upgrade their SDK without upgrading self-hosted (past 21.9.0), correct?

That is correct.

**Comment by chadwhitacre** [comment]
Okay, I think we can close here, then. Lmk if I'm missing some action item for self-hosted.
