### ISSUE TITLE
Errors-only Self-hosted

### ISSUE THREAD

**Issue by hubertdeng123** [getsentry/self-hosted#3113]
Over time, Sentry infrastructure has become larger as we’ve scaled as a company and released a plethora of features. This has created the behemoth of the present day self-hosted Sentry instance, with its 50+ docker containers. These containers eat at the RAM/CPU of servers, causing large frustration for our user base. Oftentimes, users are not even using most of the features that require all the containers up and running, so these end up as idle processes. We hear the frustration from our users and want to provide a way to deploy smaller versions of self-hosted Sentry that will delight our users that only care about errors. 

# Goals
1. Reduce friction it takes to run self-hosted for errors by reducing number of containers up and running
2. Continue to provide a way for current users to continue using all of Sentry features
3. Provide users an easier experience for running self-hosted Sentry

# Tasks

- [x] add config setting for errors only self hosted
- [x] gate frontend components behind self hosted errors only setting
- [ ] provide config for errors only self-hosted that will significantly reduce infrastructure needed
  - [ ] https://github.com/getsentry/self-hosted/pull/3190
- [ ] disable api endpoints/celery tasks related to non-errors self-hosted
- [ ] testing for self-hosted errors only

**Comment by romanstingler** [comment]
can we at least add CRON, this should be a super lightweight feature

**Comment by aldy505** [comment]
> can we at least add CRON, this should be a super lightweight feature

Cron requires some additional containers, so probably..... no? But I don't know myself, we'll see!

**Comment by aldy505** [comment]
Related https://github.com/getsentry/self-hosted/issues/2773

**Comment by aldy505** [comment]
Closing this since it's implemented already https://github.com/getsentry/self-hosted/pull/3190
