### ISSUE TITLE
Exercise install.sh in multiple environments in CI

### ISSUE THREAD

**Issue by chadwhitacre** [getsentry/self-hosted#627]
I noticed on #626 that CI only runs `install.sh` in one environment, the Travis [default](https://docs.travis-ci.com/user/reference/overview/) (Xenial at the time of writing). Seems like it'd be good to run it in multiple environments in CI, since it needs to run "everywhere" (e.g., [CentOS 7](https://github.com/getsentry/onpremise/issues/622)).

### TODO

- [x] duplicate CI in GitHub actions under Xenial: #634, #639
- [x] compare run time to Travis and consider caching
- [x] run docker in docker under GitHub actions
- [x] add CentOS 7 as a second CI environment
- [ ] add macOS as a CI environment: https://github.com/getsentry/self-hosted/pull/1587
- [x] remove Travis once we trust GitHub Actions

**Comment by chadwhitacre** [comment]
Not really possible at Travis: #628.

I think the complication is that, while afaict there are CI services that allow for running in arbitrary Docker containers, the thing-under-test is itself a Docker build ... so would we need to run Docker inside Docker? 🤔

**Comment by BYK** [comment]
Oh, I think this is a neat idea! Running docker "inside" Docker is a lot easier than you may think. Most of the time mounting `/var/run/docker.sock` into the container under the same path "just works". Combined with a switch to GitHub Actions we can support both MacOS and CentOS builds.

I'll admit that running this repo on non-Linux environments is not really a goal but it may be useful to detect incompatibilities.

**Comment by chadwhitacre** [comment]
I've updated the description with a TODO, and kicked out a first PR: #634.

**Comment by chadwhitacre** [comment]
Travis: [5m 44s](https://travis-ci.com/github/getsentry/onpremise/builds/180124681)
GitHub: [5m 2s](https://github.com/chadwhitacre/onpremise/runs/998127947)

💃

**Comment by chadwhitacre** [comment]
It occurred to me that simply adding macOS to the test matrix at GitHub might be low-hanging fruit for this issue, but, as with Travis, GitHub's macOS runners [don't](https://github.com/actions/virtual-environments/blob/9110b389998666dc0c6a8e9abd9400248bad8dba/images/macos/macos-10.15-Readme.md) have Docker installed (not surprising since it appears they [use](https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners#cloud-hosts-for-github-hosted-runners) the same underlying service [as Travis](https://www.macstadium.com/customers/travis-ci), namely, MacStadium). The custom Docker install we're already doing for Xenial is [probably also possible](https://github.com/docker/compose/releases/tag/1.24.1) for macOS—whether at Travis or GitHub, now that I think about it—but since macOS is not a priority that's probably not worth pursuing.

**Comment by BYK** [comment]
All of our engineers use macOS by default so this may actually prove worthwhile. I'll look into this next week if you don't beat me to it like you did with the GHA port @chadwhitacre 😃

**Comment by chadwhitacre** [comment]
test

**Comment by chadwhitacre** [comment]
Closing in favor of #1586.
